spring.application.name=Invoice-Management


spring.datasource.url=jdbc:postgresql://localhost:5432/invoice_management_db
spring.datasource.username=postgres
spring.datasource.password=154545!%$%$%

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true